function othercars = update_othercar_est(othercars, sim, car_nr)

% for i = 1:othercars.n
%     othercars.car{i}.pos ...
%         = update_pos(othercars.car{i}.pos, othercars.car{i}.vel, sim.T); 
%     othercars.car{i}.bd ...
%         = get_carshape(othercars.car{i}.pos ...
%         , othercars.car{i}.W, othercars.car{i}.H);
% end

othercars.car{car_nr}.pos ...
         = update_pos(othercars.car{car_nr}.pos, othercars.car{car_nr}.vel, sim.T);